'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contrapartes
    
    '''<summary>
    '''hdf_Operacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Operacion As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Usuario As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Idioma As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''upAjax_Contrapartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAjax_Contrapartes As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lcl_Descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Descripcion As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''Localize1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Localize1 As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''txt_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_buscar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_buscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gv_Contrapartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Contrapartes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_Contrapartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Contrapartes As Global.System.Web.UI.WebControls.SqlDataSource
End Class
