'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FormularioInstrumentos
    
    '''<summary>
    '''hdf_Operacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Operacion As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Usuario As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Idioma As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_CronoICT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_CronoICT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_SubCronoICT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_SubCronoICT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_OperacionPaises control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_OperacionPaises As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_NumOperativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_NumOperativo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''FK_ID_Expediente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FK_ID_Expediente As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_ID_Expediente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_ID_Expediente As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_CodTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_CodTerm As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Ingles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Ingles As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Espanol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Espanol As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Frances control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Frances As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Portuguez control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Portuguez As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lcl_Identificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Identificacion As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_PaisesInvolucrados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_PaisesInvolucrados As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Resultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Resultados As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_RecursosIICA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_RecursosIICA As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_PalabrasClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_PalabrasClave As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Enlaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Enlaces As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Descripcion As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''fv_Perfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fv_Perfil As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''gv_PalabrasClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_PalabrasClave As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_PalabrasClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_PalabrasClave As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_Descripcion_Paises control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Descripcion_Paises As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_PaisesInvolucrados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_PaisesInvolucrados As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_PaisesInvolucrados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_PaisesInvolucrados As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_ResultadosEsperados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_ResultadosEsperados As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_Resultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Resultados As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_Resultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Resultados As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_RecursosIICAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_RecursosIICAT As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_RecursosIICA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_RecursosIICA As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_RecursosIICA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_RecursosIICA As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_RecursosExternosT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_RecursosExternosT As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_RecursosExternos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_RecursosExternos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_RecursosExternos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_RecursosExternos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_KeyWords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_KeyWords As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_PalabraClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_PalabraClave As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_PalabrasClave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_PalabrasClave2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_Agrovoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Agrovoc As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''txt_PalabraBuscarAgrovoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PalabraBuscarAgrovoc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gv_PalabrasAGROVOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_PalabrasAGROVOC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_PalabrasAGROVOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_PalabrasAGROVOC As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_links control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_links As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_Participantes_Enlaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Participantes_Enlaces As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_Participantes_Enlaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Participantes_Enlaces As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sqlDS_Instrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Instrumentos As Global.System.Web.UI.WebControls.SqlDataSource
End Class
