'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InstrumentoPublico
    
    '''<summary>
    '''hdf_CronoICT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_CronoICT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_SubCronoICT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_SubCronoICT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_NumOperativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_NumOperativo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Idioma As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fv_Instrumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fv_Instrumento As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''sqlDS_Instrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Instrumentos As Global.System.Web.UI.WebControls.SqlDataSource
End Class
