'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Panel
    
    '''<summary>
    '''hdf_Operacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Operacion As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Usuario As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Idioma As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Operativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Operativo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''upAjax_Usuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAjax_Usuarios As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lcl_Descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Descripcion As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''IntroduccionExpandir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IntroduccionExpandir As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnk_BtnSeguimientp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_BtnSeguimientp As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lcl_Seguimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Seguimiento As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_Cambios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Cambios As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_Cambios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Cambios As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lnk_ListadoCompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_ListadoCompleto As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lcl_ListadoCompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_ListadoCompleto As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lnk_Estadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_Estadisticas As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lcl_Estadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Estadisticas As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Tit_Estadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Tit_Estadisticas As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''ltl_EstadoPlaneacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl_EstadoPlaneacion As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltl_Avance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl_Avance As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ltl_Avance2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl_Avance2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rpt_Resumen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpt_Resumen As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''sqlDS_Grafico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Grafico As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_Detalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Detalle As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_Estadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Estadisticas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_Instrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Instrumentos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_Cerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Cerrar As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lbl_FiltroRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FiltroRegion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_FiltroRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_FiltroRegion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl_FiltroPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FiltroPais As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_FiltroPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_FiltroPais As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlDS_FiltroPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_FiltroPais As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lbl_FiltroAgrovoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FiltroAgrovoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_FiltroAgrovoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_FiltroAgrovoc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlDS_Agrovoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Agrovoc As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lbl_FiltroFondos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FiltroFondos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_TipoFondo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TipoFondo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblBuscarpor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuscarpor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_buscar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_buscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbl_Contrapartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Contrapartes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_Contrapartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Contrapartes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlDS_Contrapartes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Contrapartes As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lbl_Recursos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Recursos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_Recursos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Recursos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl_FiltroTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FiltroTipo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_FiltroTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_FiltroTipo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlDS_Tipos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Tipos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lcl_Conteo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Conteo As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Conteo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Conteo1 As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Conteo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Conteo2 As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''gv_Identificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Identificacion As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_PanelIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_PanelIdentificacion As Global.System.Web.UI.WebControls.SqlDataSource
End Class
