'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ErrorGeneral
    
    '''<summary>
    '''lcl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Error As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''img_Informacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_Informacion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lbl_Mensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Mensaje As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_InfoContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_InfoContacto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlnk_CorreoAdministrador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnk_CorreoAdministrador As Global.System.Web.UI.WebControls.HyperLink
End Class
