'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class tableroDirectivo
    
    '''<summary>
    '''iframe_TableroDirectivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iframe_TableroDirectivo As Global.System.Web.UI.HtmlControls.HtmlIframe
    
    '''<summary>
    '''sqlDS_TipoReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_TipoReporte As Global.System.Web.UI.WebControls.SqlDataSource
End Class
