'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster
    
    '''<summary>
    '''hdf_ID_Intranet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_ID_Intranet As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''img_perfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_perfil As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''li_MenuToolbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_MenuToolbox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Tablero_Directivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Tablero_Directivo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Historico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Historico As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_ARR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_ARR As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Programas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Programas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Comercio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Comercio As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_BioEconomia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_BioEconomia As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_CambioClimatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_CambioClimatico As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_DesarrolloTerritorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_DesarrolloTerritorial As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_SAIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_SAIA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_PAEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_PAEN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_PAESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_PAESC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_FonPRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_FonPRI As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Belice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Belice As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_CR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_CR As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Guatemala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Guatemala As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Honduras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Honduras As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Nicaragua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Nicaragua As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Panama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Panama As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Salvador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Salvador As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Antigua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Antigua As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Barbados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Barbados As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Dominica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Dominica As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Guayana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Guayana As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Haiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Haiti As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Jamaica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Jamaica As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_SCN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_SCN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_SL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_SL As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Bahamas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Bahamas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_RDominicana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_RDominicana As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Granada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Granada As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Surinam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Surinam As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Trinidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Trinidad As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_SanVicente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_SanVicente As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Bolivia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Bolivia As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Colombia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Colombia As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Ecuador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Ecuador As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Peru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Peru As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Venezuela control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Venezuela As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Argentina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Argentina As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Brasil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Brasil As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Chile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Chile As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Paraguay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Paraguay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Uruguay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Uruguay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Canada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Canada As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_USA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_USA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_España control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_España As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_Mexico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_Mexico As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''li_Of_SedeCentral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li_Of_SedeCentral As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''img_IICA_Back control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_IICA_Back As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''sqlDS_Perfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Perfil As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sqlDS_RolUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_RolUsuario As Global.System.Web.UI.WebControls.SqlDataSource
End Class
